#host=42.193.245.96
#host=81.71.127.215
host=127.0.0.1
port=8777
deviceCount=15000
minReportIntervalSeconds=20
maxReportIntervalSeconds=30
reconnectDelayMillis=10000
loginRetryIntervalSeconds=20
loginRetryWindowSeconds=180
readerIdleSeconds=240
eventLoopThreads=64
