host=139.199.15.22
#host=172.16.16.19
#host=127.0.0.1
port=8777
deviceCount=60000
minReportIntervalSeconds=140
maxReportIntervalSeconds=170
reconnectDelayMillis=30000
loginRetryIntervalSeconds=20
loginRetryWindowSeconds=180
readerIdleSeconds=240
