#host=42.194.133.193
#host=test.miaoxianghuandian.com
host=fc-1.miaoxianghuandian.com
#host=127.0.0.1
#port=8777
port=2777
deviceCount=1
minReportIntervalSeconds=10
maxReportIntervalSeconds=20
reconnectDelayMillis=30000
loginRetryIntervalSeconds=20
loginRetryWindowSeconds=180
readerIdleSeconds=240
