#host=42.193.245.96
host=81.71.127.215
port=8777
deviceCount=18000
minReportIntervalSeconds=20
maxReportIntervalSeconds=30
reconnectDelayMillis=10000
loginRetryIntervalSeconds=20
loginRetryWindowSeconds=180
readerIdleSeconds=240
